### ISSUE TITLE
One small fix.

### ISSUE THREAD

**Issue by MewingsDoings** [yuv422/png2tile#2]
Something small I noticed while building this was that I had to add cstring to the includes, for strcmp, memcpy, memset to compile properly.  I'm not sure how you would choose to fix this if you do so, it's a small issue and all, but I figured you'd want to know.

**Comment by yuv422** [comment]
Hi, Thanks for the feedback. What environment / compiler are you using to compile?

**Comment by MewingsDoings** [comment]
Oh!  Of course, I totally forgot to say!  This happened with g++ on Linux Mint x86_64.

**Comment by MewingsDoings** [comment]
err... didn't mean to close it x.x

**Comment by yuv422** [comment]
This should be fixed now. :)
